### ISSUE TITLE
Widget - Images not showing up for some events. (Production)

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-calendar-widget#25]
![Image](https://github.com/culturecreates/footlight-calendar-widget/assets/139208017/d568bc7c-5012-424d-a239-1ac05293106e)

**Comment by SyamBabu-M** [comment]
@troughc This has been fixed. This was caused because we were passing the staging API.  Please test this in CMS production itself.

**Comment by troughc** [comment]
Perfect @SyamBabu-M  !! Tested Production in chrome and Safari: PASSED
closing as this is already in Production
