### ISSUE TITLE
Listing Widget remove global CSS override

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-widget#46]
As a developer integrating the listing widget with <DIV> I do not want my webpage Font to be overridden with a global font in the listing-widget CSS, or any other global overrides. I should be able to have my own CSS for my webpage without anything changing when I link the listing-widet CSS.

**Comment by saumier** [comment]
@troughc Same comment as for the other listing-widget issue. These are high priority because they are for Destination Canada's website.

**Comment by SyamBabu-M** [comment]
This can be tested using the staging listing widget. 
Here is the PR I raised for production release, https://github.com/culturecreates/footlight-calendar-widget/pull/47
